name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Install Bats
          run: sudo apt-get update && sudo apt-get install -y bats

        - name: Run ShellCheck
          run: shellcheck auto-commit.sh

        - name: Run tests
          run: |
            tmp="$(mktemp -d)"
            git init "$tmp"
            cd "$tmp"
            bats "$GITHUB_WORKSPACE/tests"
